title: ДИПЛОМЕН ПРОЕКТ 2024
description: Проектиране на аудио ефект за електрическа китара
author: Вяра Трифонова
theme: jekyll-theme-minimal
url: "https://viara-trifonova.github.io/"
baseurl: "/diplomna_public"
header_pages:
- index.md
- aim.md
- result.md
- sch.md
- pcb.md
- box.md
- rec.md
- file.md
footer: viaratrifonova@gmail.com © viara-trifonova 2024
