title: ДИПЛОМЕН ПРОЕКТ 2024
description: Проектиране на аудио ефект за електрическа китара
baseurl: ""  # Оставете празно, ако сайтът е на основния домейн
url: "https://viara-trifonova.github.io"  # Заменете с вашето потребителско име
theme: jekyll-theme-slate  # Използваме тема

# Навигация (табове)
header_pages:
  - index.md
  - tsel-na-diplomnata-rabota.md
  - recenziya.md
  - shema.md
  - platka.md
  - korpus.md
